export const data = [
  {
    img_link: "springbee.jpg",
    heading: "SpringBee",
    detail: "It is a lms portal website.",
    tech: "Next, typescript, node, express, socket, redis, mongoDb.",
    git_link: "https://github.com/aryantiwari8736/client",
    proj_link: "https://springbee.live",
  },
  {
    img_link: "technocrats.jpg",
    heading: "Technocrats",
    detail: "Official website of Technocrats club kiet",
    tech: "ReactJs, Javscript, Tailwind CSS.",
    git_link: "https://github.com/aryantiwari8736/client",
    proj_link: "https://technocrats.live/",
  },
  {
    img_link: "ching.jpg",
    heading: "foodspy",
    detail: "It is a food ordering website like zomato ,swiggy etc.",
    tech: "ReactJs , Redux , JSX , Css , Javascript",
    git_link: "https://github.com/aryantiwari8736/FoodSpy",
    proj_link: "https://foodspy.netlify.app/",
  },
  {
    img_link: "epo.png",
    heading: "Fest-Website",
    detail: "This is a  Annual Fest (Prastuti) Website of My college.",
    tech: "ReactJs , Redux , JSX , Css , Javascript",
    git_link: "https://github.com/aryantiwari8736/Prastuti",
    proj_link: "https://epoqueatprastuti.netlify.app/",
  },
  {
    img_link: "brain.jpg",
    heading: "BrainBIts",
    detail: "This is a Community Website,Using by more than 500 students ",
    tech: "ReactJs , JSX , Css , Javascript",
    git_link: "https://github.com/aryantiwari8736/BrainBits",
    proj_link: "https://www.thebrainbits.com/",
  },
];
